let isLogin = false;
let currentUserData=null;

function toggleAuth() {
    isLogin = !isLogin;
    document.getElementById('form-title').innerText = isLogin ? "Login" : "Sign Up";
    document.getElementById('btn-text').innerText = isLogin ? "Login" : "Register";

    const extraFields = ['name', 'pass_mobile', 'age', 'par_mobile', 'country', 'state', 'district'];
    extraFields.forEach(id => {
        document.getElementById(id).classList.toggle('hidden', isLogin);
    });
}

async function findTrip() {
    const originVal = document.getElementById('origin').value;
    const destVal = document.getElementById('destination').value;
    const resultsDiv = document.getElementById('results');
    
    if (!originVal || !destVal) {
        alert("Please enter both origin and destination");
        return;
    }

    try {
        const url = `https://jetswift-backend.onrender.com/flights/search?origin=${originVal}&destination=${destVal}`;
        const response = await fetch(url);
        const flights = await response.json();

        resultsDiv.innerHTML = ""; // Clear old results

        if (flights.length === 0) {
            resultsDiv.innerHTML = "<p>No flights found for this destination.</p>";
            return;
        }

        flights.forEach(flight => {
            const flightInfo = `
                <div style="border: 1px solid #ddd; padding: 15px; margin-top: 10px; border-radius: 8px; color: black; background: #fff; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
                    <strong>${flight.airline}</strong> - ${flight.flightNumber}<br>
                    From: ${flight.origin} To: ${flight.destination}<br>
                    Price: ₹${flight.price} | Date: ${flight.date}<br>
                    <button onclick="bookTicket('${flight.airline}', '${flight.flightNumber}', '${flight.origin}', '${flight.destination}', '${flight.price}', '${flight.date}')" 
                            style="margin-top:10px; background: #28a745; padding: 8px; font-size: 14px;">
                        Book & Download Ticket
                    </button>
                </div>
            `;
            resultsDiv.innerHTML += flightInfo;
        });
    } catch (err) {
        console.error("Error fetching flights:", err);
    }
}

// Function to generate and download the ticket
async function bookTicket(airline, flightNo, from, to, price, date) {
  // 1. Call your backend to create an order
  const response = await fetch('https://jetswift-backend.onrender.com/create-order', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ amount: price })
  });
  const order = await response.json();

  // 2. Configure Razorpay options
  const options = {
    key: "rzp_test_Skn83hTPivycrT", 
    amount: order.amount,
    currency: "INR",
    name: "SkyHigh Air",
    description: `Booking for ${flightNo}`,
    order_id: order.id, // The ID generated by your backend
    handler: function (response) {
      // This runs AFTER successful payment
      alert("Payment Successful! Transaction ID: " + response.razorpay_payment_id);
      
      // Trigger your existing PDF ticket generation logic here
      generatePDFTicket(airline, flightNo, from, to, price, date);
    },
    prefill: {
      name: currentUserData.name, // Using your existing user profile data
      email: currentUserData.email,
    },
    theme: { color: "#003580" } // Matching your current UI color
  };

  const rzp = new window.Razorpay(options);
  rzp.open();
}

function generatePDFTicket(airline, flightNo, from, to, price, date)
  {   
    const ticketContent = `
    -------------------------------------------
               SKYHIGH AIR  TICKET(g)
    -------------------------------------------
    PASSENGER DETAILS:
    Name: ${currentUserData.name}
    Age: ${currentUserData.age}
    Mobile: ${currentUserData.pass_mobile}
    Address: ${currentUserData.address}
    
    FLIGHT DETAILS:
    Airline: ${airline}
    Flight Number: ${flightNo}
    Route: ${from} -> ${to}
    Date: ${date}
    Total Paid: ₹${price}
    
    Status: CONFIRMED
    -------------------------------------------
    Thank you for choosing SkyHigh!
    `;

    // Create a hidden link to trigger the download
    const { jsPDF } = window.jspdf; // Required to access the library
    const doc = new jsPDF();
    doc.text(ticketContent, 10, 10);
    doc.save(`Ticket_${flightNo}.pdf`);
    // ---------------------------------------------------------

    alert("Ticket Booked Successfully! Your download has started.");

    findTrip();
}

async function submitAuth() {
    const name = document.getElementById('name').value;
    const email = document.getElementById('email').value;
    const password = document.getElementById('password').value;
    const age = document.getElementById('age').value;
    const pass_mobile = document.getElementById('pass_mobile').value;
    const par_mobile = document.getElementById('par_mobile').value;
    const country = document.getElementById('country').value;
    const state = document.getElementById('state').value;
    const district = document.getElementById('district').value;

    const endpoint = isLogin ? '/login' : '/register';
    const bodyData = isLogin ? { email, password } : { name, email, password, age, pass_mobile, par_mobile, country, state, district };

  try
  {

    const response = await fetch(`https://jetswift-backend.onrender.com${endpoint}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(bodyData)
    });

    const data = await response.json();
    if (response.ok) 
        {
        if (isLogin) 
        {
            currentUserData = data.user;   //store profile data
            document.getElementById('auth-box').classList.add('hidden');
            document.getElementById('dashboard').classList.remove('hidden');
            document.getElementById('user-name').innerText = data.user.name;
        } 
        else 
         {
            alert("Registration complete! Please login.");
            toggleAuth();
         }
    } 
    else 
    {
        alert(data.error || "Something went wrong");
    }

 }
  catch(err)
   {
      console.error("Auth Error : ",err);
   }

}

function showProfile() {
    document.getElementById('booking-section').classList.add('hidden');
    document.getElementById('profile-section').classList.remove('hidden');
    
    document.getElementById('p-age').innerText = currentUserData.age;
    document.getElementById('p-mobile').innerText = currentUserData.pass_mobile;
    document.getElementById('p-address').innerText = currentUserData.address;
}

function hideProfile() {
    document.getElementById('profile-section').classList.add('hidden');
    document.getElementById('booking-section').classList.remove('hidden');
}
